version: "3.9"

services:
  nginx:
    image: "nginx:alpine-slim"
    expose:
      - "80"
    volumes:
      - ..:/var/www
      - ./logs/nginx:/var/log/nginx
      - ./nginx:/etc/nginx/conf.d
    working_dir: /var/www

  php-fpm:
    build:
      context: ./php-fpm
    expose:
      - "9000"
    volumes:
      - ../:/var/www

  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpsw
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    expose:
      - 3306

  # redis:
  #   image: 'redis:alpine'
  #   expose:
  #     - 6379
  #   volumes:
  #     - redis:/data # Remember to uncomment redis in the volumes section

networks:
  default:
    name: skipper_network
    external: true

volumes:
  mysql:
    driver: "local"
  # redis:
  #   driver: "local"
